<a href="https://colab.research.google.com/github/DaoLua/Opella./blob/Data_Logger/Data_Logger.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
%pip install tabula-py jpype1 PyPDF2 pandas

import tabula
import jpype
import pandas as pd
import re
import os
import glob
from PyPDF2 import PdfReader
from IPython.display import display

print("\n\nChào mừng bạn đến với tool phân tích TOR từ datalogger.")

def get_user_input():
    print("\nBước 1: Thời gian nhập nguyên liệu vào kho (UTC+0)")
    while True:
        try:
            input_date_str = input("Nhập ngày (DD/MM/YYYY): ")
            input_time_str = input("Nhập giờ (HH:MM): ")
            global_cutoff_datetime = pd.to_datetime(f"{input_date_str} {input_time_str}:00", format='%d/%m/%Y %H:%M:%S')
            break
        except ValueError:
            print("Sai định dạng. Vui lòng nhập lại.")

    print("\nBước 2: Giới hạn nhiệt độ của nguyên liệu")
    while True:
        try:
            tor_threshold_temp = float(input("Nhập nhiệt độ (°C): "))
            break
        except ValueError:
            print("Sai định dạng. Vui lòng nhập lại.")

    print("\nBước 3: Định dạng ngày tháng trong file PDF\n1: yy/mm/dd\n2: yy/dd/mm\n3: dd/mm/yy\n4: mm/dd/yy")
    while True:
        choice = input("Nhập lựa chọn của bạn (1-4): ")
        format_dict = {
            '1': ('%y/%m/%d %H:%M:%S', 'yy/mm/dd'),
            '2': ('%y/%d/%m %H:%M:%S', 'yy/dd/mm'),
            '3': ('%d/%m/%y %H:%M:%S', 'dd/mm/yy'),
            '4': ('%m/%d/%y %H:%M:%S', 'mm/dd/yy')
        }
        if choice in format_dict:
            return global_cutoff_datetime, tor_threshold_temp, format_dict[choice][0], format_dict[choice][1]
        print("Lựa chọn không hợp lệ. Vui lòng nhập số từ 1 đến 4.")

def process_pdf(pdf_path, logger_id, global_cutoff_datetime, tor_threshold_temp, pdf_date_format, pdf_date_label):
    print(f"\nĐang xử lý file: {logger_id}")

    try:
        with open(pdf_path, 'rb') as f:
            total_pages = len(PdfReader(f).pages)
        dfs = tabula.read_pdf(pdf_path, pages=f"2-{total_pages}", stream=True, multiple_tables=True)
    except Exception as e:
        print(f"Lỗi xử lý PDF {logger_id}: {e}")
        return None, None, None, None, None, None

    all_reshaped_chunks = []
    for page_df in dfs:
        for i in range(0, page_df.shape[1], 3):
            if i + 2 < page_df.shape[1]:
                chunk = page_df.iloc[:, i:i+3].copy()
                chunk.columns = ['raw_col1', 'raw_col2', 'raw_col3']
                all_reshaped_chunks.append(chunk)

    if not all_reshaped_chunks:
        return None, None, None, None, None, None

    raw_long_df = pd.concat(all_reshaped_chunks, ignore_index=True)
    all_records = []
    pattern = re.compile(r'(\d{2}/\d{2}/\d{2})?\s+(\d{2}:\d{2}:\d{2})\s+([\d\.\-]+)')

    combined_series = raw_long_df['raw_col1'].fillna('') + ' ' + raw_long_df['raw_col2'].fillna('') + ' ' + raw_long_df['raw_col3'].fillna('')

    for text in combined_series:
        for date_val, time_val, temp_val in pattern.findall(text):
            all_records.append({'date': date_val, 'time': time_val, 'temperature': temp_val})

    if not all_records:
        return None, None, None, None, None, None

    datalogger = pd.DataFrame(all_records)
    datalogger['datetime'] = pd.to_datetime(datalogger['date'] + ' ' + datalogger['time'], format=pdf_date_format, errors='coerce')
    datalogger['temperature'] = pd.to_numeric(datalogger['temperature'], errors='coerce').astype('float16')
    datalogger.dropna(subset=['datetime', 'temperature'], inplace=True)
    datalogger.sort_values('datetime', inplace=True, ignore_index=True)
    datalogger.drop_duplicates(subset=['datetime', 'temperature'], keep='first', inplace=True)

    datalogger_filtered = datalogger[datalogger['datetime'] <= global_cutoff_datetime].reset_index(drop=True)

    if datalogger_filtered.empty:
        return None, None, None, None, None, None

    min_temp = datalogger_filtered['temperature'].min()
    max_temp = datalogger_filtered['temperature'].max()
    min_temp_datetime = datalogger_filtered.loc[datalogger_filtered['temperature'].idxmin(), 'datetime']
    max_temp_datetime = datalogger_filtered.loc[datalogger_filtered['temperature'].idxmax(), 'datetime']

    datalogger_filtered['is_tor'] = datalogger_filtered['temperature'] > tor_threshold_temp
    tor_periods = []
    start_time = None

    for i in range(len(datalogger_filtered)):
        is_current_tor = datalogger_filtered.loc[i, 'is_tor']
        is_previous_tor = False if i == 0 else datalogger_filtered.loc[i-1, 'is_tor']
        is_next_tor = False if i == len(datalogger_filtered) - 1 else datalogger_filtered.loc[i+1, 'is_tor']

        if is_current_tor and not is_previous_tor:
            start_time = datalogger_filtered.loc[i, 'datetime']

        if is_current_tor and not is_next_tor and start_time is not None:
            if i == len(datalogger_filtered) - 1:
                end_time = global_cutoff_datetime
            else:
                end_time = datalogger_filtered.loc[i+1, 'datetime']
            tor_periods.append({'TOR start': start_time, 'TOR stop': end_time})
            start_time = None

    tor_df = pd.DataFrame(tor_periods)
    final_tor_df = None
    total_tor_file = pd.Timedelta(seconds=0)

    if not tor_df.empty:
        tor_df['Excursion duration'] = tor_df['TOR stop'] - tor_df['TOR start']
        tor_df['Excursion duration_str'] = tor_df['Excursion duration'].apply(lambda x: f'{x.days*24 + x.seconds//3600:02d}:{x.seconds%3600//60:02d}')

        tor_df = pd.merge(tor_df, datalogger_filtered[['datetime', 'temperature']], left_on='TOR start', right_on='datetime', how='left')
        tor_df.rename(columns={'temperature': 'temperature at tor start'}, inplace=True)
        tor_df.drop(columns=['datetime'], inplace=True)

        tor_df = pd.merge(tor_df, datalogger_filtered[['datetime', 'temperature']], left_on='TOR stop', right_on='datetime', how='left')
        tor_df['temperature'] = tor_df['temperature'].fillna(datalogger_filtered['temperature'].iloc[-1])
        tor_df.rename(columns={'temperature': 'temperature at tor stop'}, inplace=True)
        tor_df.drop(columns=['datetime'], inplace=True)

        final_tor_df = tor_df[['TOR start', 'temperature at tor start', 'TOR stop', 'temperature at tor stop', 'Excursion duration_str']].copy()
        final_tor_df.rename(columns={'Excursion duration_str': 'Excursion duration'}, inplace=True)
        final_tor_df['Logger ID'] = logger_id.replace('.pdf', '')

        total_tor_file = tor_df['Excursion duration'].sum()

    return final_tor_df, total_tor_file, min_temp, min_temp_datetime, max_temp, max_temp_datetime

def format_timedelta(td):
    total_seconds = td.total_seconds()
    return f"{int(total_seconds // 86400):02d}:{int((total_seconds % 86400) // 3600):02d}:{int((total_seconds % 3600) // 60):02d}"

datalogger_dir = '/content/datalogger/'
os.makedirs(datalogger_dir, exist_ok=True)
pdf_files = [f for f in os.listdir(datalogger_dir) if f.endswith('.pdf')]

all_processed_dataframes = []
total_tor_data = []

global_cutoff_datetime, tor_threshold_temp, pdf_date_format, pdf_date_label = get_user_input()
date_time_format = pdf_date_format.replace(':%S', '')

for pdf_file in pdf_files:
    pdf_path = os.path.join(datalogger_dir, pdf_file)
    final_tor_df, total_tor, min_temp, min_temp_dt, max_temp, max_temp_dt = process_pdf(
        pdf_path, pdf_file, global_cutoff_datetime, tor_threshold_temp, pdf_date_format, pdf_date_label
    )

    if final_tor_df is not None:
        all_processed_dataframes.append(final_tor_df)
    if min_temp is not None:
         total_tor_data.append({
            'Logger ID': pdf_file.replace('.pdf', ''),
            'Total TOR': total_tor,
            'Min Temperature': min_temp,
            'Min Temp Datetime': min_temp_dt,
            'Max Temperature': max_temp,
            'Max Temp Datetime': max_temp_dt
        })

if all_processed_dataframes:
    combined_datalogger_df = pd.concat(all_processed_dataframes, ignore_index=True)
    total_tor_summary_df = pd.DataFrame(total_tor_data)

    total_tor_summary_df['Tổng thời gian TOR (dd:hh:mm)'] = total_tor_summary_df['Total TOR'].apply(format_timedelta)
    total_tor_summary_df[f'Ngày giờ nhiệt độ Min ({pdf_date_label} hh:mm)'] = total_tor_summary_df['Min Temp Datetime'].dt.strftime(date_time_format)
    total_tor_summary_df[f'Ngày giờ nhiệt độ Max ({pdf_date_label} hh:mm)'] = total_tor_summary_df['Max Temp Datetime'].dt.strftime(date_time_format)
    total_tor_summary_df = total_tor_summary_df[['Logger ID', 'Tổng thời gian TOR (dd:hh:mm)', 'Min Temperature', f'Ngày giờ nhiệt độ Min ({pdf_date_label} hh:mm)', 'Max Temperature', f'Ngày giờ nhiệt độ Max ({pdf_date_label} hh:mm)']]

    combined_datalogger_df['Số thứ tự'] = combined_datalogger_df.groupby('Logger ID').cumcount() + 1
    combined_datalogger_df[f'Thời gian bắt đầu TOR ({pdf_date_label} hh:mm)'] = combined_datalogger_df['TOR start'].dt.strftime(date_time_format)
    combined_datalogger_df[f'Thời gian kết thúc TOR ({pdf_date_label} hh:mm)'] = combined_datalogger_df['TOR stop'].dt.strftime(date_time_format)
    combined_datalogger_df.rename(columns={'Excursion duration': 'Thời gian vượt ngưỡng (hh:mm)'}, inplace=True)

    final_combined_df = combined_datalogger_df[['Logger ID', 'Số thứ tự', f'Thời gian bắt đầu TOR ({pdf_date_label} hh:mm)', 'temperature at tor start', f'Thời gian kết thúc TOR ({pdf_date_label} hh:mm)', 'temperature at tor stop', 'Thời gian vượt ngưỡng (hh:mm)']]

    print("\n--- Chi tiết các lần vượt ngưỡng TOR ---")
    display(final_combined_df)

    print("\n--- Tóm tắt tổng TOR ---")
    display(total_tor_summary_df)

    output_excel_path = "/content/datalogger/tor_analysis_results.xlsx"
    with pd.ExcelWriter(output_excel_path) as writer:
        final_combined_df.to_excel(writer, sheet_name='Chi tiết TOR', index=False)
        total_tor_summary_df.to_excel(writer, sheet_name='Tóm tắt tổng TOR', index=False)
    print(f"\nKết quả đã xuất xong tại: {output_excel_path}")

    print("\nĐang dọn dẹp các tệp PDF gốc...")
    for pdf_file_path in glob.glob(os.path.join(datalogger_dir, '*.pdf')):
        try:
            os.remove(pdf_file_path)
            print(f"Đã xóa: {os.path.basename(pdf_file_path)}")
        except OSError as e:
            print(f"Không thể xóa {pdf_file_path}: {e}")
else:
    print("\nKhông có dữ liệu nào được xử lý từ các file PDFs.")

Requirement already satisfied: tabula-py in /usr/local/lib/python3.12/dist-packages (2.10.0)
Requirement already satisfied: jpype1 in /usr/local/lib/python3.12/dist-packages (1.7.1)
Requirement already satisfied: PyPDF2 in /usr/local/lib/python3.12/dist-packages (3.0.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>1.24.4 in /usr/local/lib/python3.12/dist-packages (from tabula-py) (2.0.2)
Requirement already satisfied: distro in /usr/local/lib/python3.12/dist-packages (from tabula-py) (1.9.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from jpype1) (26.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)


Chào mừng bạn đến với tool phân tích TOR từ datalogger.

Bước 1: Thời gian nhập nguyên liệu vào kho (UTC+0)
Nhập ngày (DD/MM/YYYY): 13/07/2026
Nhập giờ (HH:MM): 06:24

Bước 2: Giới hạn nhiệt độ của nguyên liệu
Nhập nhiệt độ (°C): 8

Bước 3: Định dạng ngày tháng trong file PDF
1: yy/mm/dd
2: yy/dd/mm
3: dd/mm/yy
4: mm/dd/yy
Nhập lựa chọn của bạn (1-4): 4

WARNING:PyPDF2._reader:incorrect startxref pointer(2)

Đang xử lý file: 250601982H.pdf

WARNING:PyPDF2._reader:incorrect startxref pointer(2)

Đang xử lý file: 250601978H.pdf

WARNING:PyPDF2._reader:incorrect startxref pointer(2)

Đang xử lý file: 250601985H.pdf

WARNING:PyPDF2._reader:incorrect startxref pointer(2)

Đang xử lý file: 250601980H.pdf

WARNING:PyPDF2._reader:incorrect startxref pointer(2)

Đang xử lý file: 250601979H.pdf

WARNING:PyPDF2._reader:incorrect startxref pointer(2)

Đang xử lý file: 250601983H.pdf

WARNING:PyPDF2._reader:incorrect startxref pointer(2)

Đang xử lý file: 250601977H.pdf

WARNING:PyPDF2._reader:incorrect startxref pointer(2)

Đang xử lý file: 250601976H.pdf

--- Chi tiết các lần vượt ngưỡng TOR ---

/usr/local/lib/python3.12/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: overflow encountered in cast
  has_large_values = (abs_vals > 1e6).any()

,Logger ID,Số thứ tự,Thời gian bắt đầu TOR (mm/dd/yy hh:mm),temperature at tor start,Thời gian kết thúc TOR (mm/dd/yy hh:mm),temperature at tor stop,Thời gian vượt ngưỡng (hh:mm)
0,250601982H,1,07/04/26 05:56,8.101562,07/04/26 07:01,7.300781,01:05
1,250601982H,2,07/04/26 07:36,8.101562,07/04/26 07:51,8.000000,00:15
2,250601982H,3,07/06/26 16:21,8.101562,07/06/26 18:41,8.000000,02:20
3,250601982H,4,07/06/26 22:56,8.101562,07/07/26 03:06,8.000000,04:10
4,250601982H,5,07/07/26 17:01,8.101562,07/07/26 20:16,8.000000,03:15
5,250601982H,6,07/08/26 05:06,8.296875,07/08/26 06:41,8.000000,01:35
6,250601982H,7,07/13/26 06:16,10.500000,07/13/26 06:24,15.500000,00:07
7,250601978H,1,07/04/26 05:36,8.101562,07/04/26 10:16,7.800781,04:40
8,250601978H,2,07/06/26 13:21,8.203125,07/06/26 17:56,7.898438,04:35
9,250601978H,3,07/07/26 23:41,8.203125,07/08/26 12:06,8.000000,12:25
10,250601978H,4,07/08/26 12:16,8.101562,07/08/26 12:36,8.000000,00:20
11,250601978H,5,07/13/26 06:21,13.296875,07/13/26 06:24,13.296875,00:02
12,250601985H,1,07/04/26 05:28,8.203125,07/04/26 08:23,7.898438,02:55
13,250601985H,2,07/06/26 23:08,8.203125,07/06/26 23:13,6.398438,00:05
14,250601985H,3,07/07/26 02:23,8.296875,07/07/26 02:48,7.699219,00:25
15,250601985H,4,07/07/26 16:58,8.101562,07/07/26 19:48,8.000000,02:50
16,250601985H,5,07/08/26 00:28,8.101562,07/08/26 09:18,8.000000,08:50
17,250601985H,6,07/08/26 09:28,8.101562,07/08/26 09:33,8.000000,00:05
18,250601985H,7,07/08/26 10:18,8.101562,07/08/26 10:48,8.000000,00:30
19,250601985H,8,07/13/26 06:18,15.000000,07/13/26 06:24,15.000000,00:05
20,250601980H,1,07/04/26 05:47,8.203125,07/04/26 08:27,8.000000,02:40
21,250601980H,2,07/06/26 14:42,8.101562,07/06/26 19:07,8.000000,04:25
22,250601980H,3,07/06/26 23:02,8.500000,07/06/26 23:12,7.601562,00:10
23,250601980H,4,07/07/26 02:12,8.796875,07/07/26 03:12,8.000000,01:00
24,250601980H,5,07/07/26 16:37,8.203125,07/08/26 11:42,8.000000,19:05
25,250601980H,6,07/13/26 06:17,12.898438,07/13/26 06:24,19.093750,00:06
26,250601979H,1,07/04/26 05:54,8.203125,07/04/26 07:49,7.898438,01:55
27,250601979H,2,07/04/26 08:04,8.203125,07/04/26 09:34,8.000000,01:30
28,250601979H,3,07/07/26 18:04,8.101562,07/07/26 19:24,8.000000,01:20
29,250601979H,4,07/08/26 02:04,8.101562,07/08/26 02:09,8.000000,00:05
30,250601979H,5,07/08/26 03:19,8.101562,07/08/26 08:34,8.000000,05:15
31,250601979H,6,07/08/26 08:39,8.101562,07/08/26 09:09,8.000000,00:30
32,250601979H,7,07/08/26 09:14,8.101562,07/08/26 09:24,8.000000,00:10
33,250601979H,8,07/08/26 09:29,8.101562,07/08/26 09:34,8.000000,00:05
34,250601979H,9,07/08/26 10:19,8.101562,07/08/26 11:09,8.000000,00:50
35,250601979H,10,07/13/26 06:19,13.000000,07/13/26 06:24,13.000000,00:04
36,250601983H,1,07/04/26 05:53,8.101562,07/04/26 08:18,7.898438,02:25
37,250601983H,2,07/06/26 23:18,8.898438,07/07/26 03:28,7.800781,04:10
38,250601983H,3,07/08/26 05:28,8.101562,07/08/26 08:58,8.000000,03:30
39,250601983H,4,07/13/26 06:18,10.203125,07/13/26 06:24,17.703125,00:05
40,250601977H,1,07/04/26 07:23,8.101562,07/04/26 09:43,7.800781,02:20
41,250601977H,2,07/06/26 14:43,8.101562,07/06/26 15:48,7.601562,01:05
42,250601977H,3,07/07/26 02:23,8.703125,07/07/26 02:58,7.898438,00:35
43,250601977H,4,07/07/26 16:53,8.101562,07/07/26 20:13,8.000000,03:20
44,250601977H,5,07/07/26 20:28,8.101562,07/07/26 20:38,7.800781,00:10
45,250601977H,6,07/08/26 05:58,8.398438,07/08/26 08:13,8.000000,02:15
46,250601977H,7,07/13/26 06:23,15.898438,07/13/26 06:24,15.898438,00:00
47,250601976H,1,07/04/26 07:12,8.101562,07/04/26 07:57,7.898438,00:45
48,250601976H,2,07/06/26 22:57,8.398438,07/07/26 03:07,7.601562,04:10
49,250601976H,3,07/07/26 17:07,8.203125,07/07/26 20:12,7.898438,03:05
50,250601976H,4,07/08/26 00:32,8.101562,07/08/26 08:27,8.000000,07:55
51,250601976H,5,07/13/26 06:17,14.601562,07/13/26 06:24,19.500000,00:06

--- Tóm tắt tổng TOR ---

/usr/local/lib/python3.12/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: overflow encountered in cast
  has_large_values = (abs_vals > 1e6).any()

,Logger ID,Tổng thời gian TOR (dd:hh:mm),Min Temperature,Ngày giờ nhiệt độ Min (mm/dd/yy hh:mm),Max Temperature,Ngày giờ nhiệt độ Max (mm/dd/yy hh:mm)
0,250601982H,00:12:47,0.799805,07/04/26 01:51,15.500000,07/13/26 06:21
1,250601978H,00:22:02,1.099609,07/07/26 06:16,16.703125,07/08/26 05:31
2,250601985H,00:15:45,0.899902,07/05/26 06:08,15.000000,07/13/26 06:18
3,250601980H,01:03:26,0.899902,07/04/26 01:52,19.093750,07/13/26 06:22
4,250601979H,00:11:44,1.200195,07/04/26 22:34,13.000000,07/13/26 06:19
5,250601983H,00:10:10,0.799805,07/04/26 22:53,17.703125,07/13/26 06:23
6,250601977H,00:09:45,1.299805,07/05/26 00:23,15.898438,07/13/26 06:23
7,250601976H,00:16:01,-1.299805,07/04/26 01:57,19.500000,07/13/26 06:22

Kết quả đã xuất xong tại: /content/datalogger/tor_analysis_results.xlsx

Đang dọn dẹp các tệp PDF gốc...
Đã xóa: 250601982H.pdf
Đã xóa: 250601978H.pdf
Đã xóa: 250601985H.pdf
Đã xóa: 250601980H.pdf
Đã xóa: 250601979H.pdf
Đã xóa: 250601983H.pdf
Đã xóa: 250601977H.pdf
Đã xóa: 250601976H.pdf